### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by Chirag018**
## Description

I have modified some UI changes on the header, to look moderate over alignment with color changes.

### CODE REVIEW

**Review by emudoteth — CHANGES_REQUESTED** [review]
looks like there is a lil conflict 
image

**Review by escottalexander — CHANGES_REQUESTED** [review]
I don't think that hover color is being used other places. I think a better improvement would be to make the light/dark mode icon have the same hover color that the ballot and wallet buttons currently do.

**Comment by Chirag018** [comment]
In dark mode, the button color is blank white, which displays nothing
Before changes:
Screenshot 2023-09-09 at 5 49 25 PM

After changes:
Screenshot 2023-09-09 at 5 49 44 PM

**Comment by escottalexander** [comment]
> In dark mode, the button color is blank white when hovering, which displays nothing Before changes: Screenshot 2023-09-09 at 5 49 25 PM
> 
> After changes: Screenshot 2023-09-09 at 5 49 44 PM

Ah I see. That is a great improvement. Any way we can only let it be that hover color when dark mode is in use?

**Comment by Chirag018** [comment]
Okay, but still color looks good even in white mode, if not will have a look at changing it!
before:
Screenshot 2023-09-09 at 6 48 53 PM

after:
Screenshot 2023-09-09 at 6 48 33 PM

**Comment by ZakGriffith** [comment]
The changes to the View Ballot and Address button in both light and dark mode look great!  I think one last thing is the set the hover colors of the light/dark mode buttons have the same color as the View Ballot and Address buttons as @escottalexander mentioned.  Once that's in, we're ready to rock.

**Comment by ZakGriffith** [comment]
After taking another look at this, I prefer bg-slate-200 as the hover color in light mode, and the current dark mode hover color you have for all three buttons (View Ballot, Rainbow Connect, and Dark/Light mode).

**Comment by Chirag018** [comment]
Screenshot 2023-09-17 at 5 52 35 PM
Screenshot 2023-09-17 at 5 52 43 PM
Screenshot 2023-09-17 at 5 52 49 PM

**Review by ZakGriffith — APPROVED** [review]
This looks good!  A few issues when using Firefox, but I will create a new issue for that.

**Review by emudoteth — APPROVED** [review]
reviewed and approved per Zak

**Review by emudoteth — APPROVED** [review]
yup

**Pull request merged**
