### PR TITLE
Solving Dark Mode Issues #67 attempt

### PR DESCRIPTION
**Pull request by luloxi**
## Description

_Did a little change in globals.css and the Header.tsx to solve what was specified in [this](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/67) issue_

## Related Issues

_Closes #67_

### CODE REVIEW

**Comment by ZakGriffith** [comment]
@luloxi Added some comments to the Issue.  Meant to do it on this PR, my bad!

**Comment by luloxi** [comment]
@ZakGriffith Pushed a new commit solving the issues mentioned [here](https://github.com/scaffold-eth/OP-RetroPGF3-Discovery-Voting/issues/67#issuecomment-1730003373)!

**Review by escottalexander — COMMENTED** [review]
This looks so good. Confirmed that Zaks change requests have been addressed. I did find just two more issues:
image
I applied the hover effect to each of these elements for comparison. The only issue if that the background color doesn't match for the dark/light mode button and secondly the shuffle button text should be black on hover. That is all I can find. Nice work. So close on this one.

**Comment by luloxi** [comment]
@escottalexander The issues you mentioned have been addressed in my last PR :smile:

**Review by escottalexander — APPROVED** [review]
LGTM!

**Pull request merged**
