### PR TITLE
List sharing modal update

### PR DESCRIPTION
**Pull request by KcPele**
## Description
List sharing modal  updated #157 
_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by KcPele** [comment]
Screenshot from 2023-11-28 09-10-23
Updated

**Comment by ZakGriffith** [comment]
Nice!  I think it would be good to update these buttons as well

image

**Comment by KcPele** [comment]
Screenshot from 2023-11-29 07-35-43

updated

**Comment by ZakGriffith** [comment]
After playing around with the buttons here is what I feel is best for them.  When viewing your ballot, it should be like this:

image

But with the Submit ballot on the right and the Share as list button on the left.  Submit button should be the red background with the darker red mouseover background that is currently found on the cancel button here https://op-retropgf3-discovery-voting.vercel.app/ when you've clicked on My Ballot - Share as List.  

The Share as List button should be the black background with the current mouseover color you have it.

This is your current buttons when clicking into the Share as List:

image

These should have the same rounded edges that all the other buttons have, and both be on the right, similar to how it is currently in the My Ballot page.  It appears that currently the Cancel button is to the left and the Share List button is to the right.

The color scheme of these buttons should be just like on the My Ballot page where the Share List will be Red with a darker red mouseover, and the Cancel button will be Black with the grey mouseover.

Once more cool thing to add is in the mouseover colors on the Projects and Lists pages.  Currently the Projects page "Add To Ballot" buttons don't have a mouseover color, and the "Lists" page has a blue/grey mouse over on the same buttons.  Both can be updated with the same mouseover color of dark red mentioned in the above changes while leaving the regular background the OP red.

Note these are all in light mode.  Have not yet tested the buttons in dark mode.

Let me know if you have any questions on these updates, and thank you!

**Comment by KcPele** [comment]
It has been updated as requested

**Comment by ZakGriffith** [comment]
Buttons colors and shapes are looking great!  Once last thing is to put the Share List button on the right and the Cancel button on the left as it was before.  They are swapped here:

image

**Comment by KcPele** [comment]
Done

**Pull request merged**
