### PR TITLE
project icon and image updated

### PR DESCRIPTION
**Pull request by KcPele**
## Description
Updated the project image and icon to fit the design
_Concise description of proposed changes, We recommend using screenshots and videos for better description_
After
Screenshot from 2023-10-17 19-16-22

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Comment by ZakGriffith** [comment]
The image looks great, but something is weird about the icon  It looks like some of the bottom is cut off, and it is stretched horizontally.  It might be good to keep the edges as seen here: 
image
And then the icon can be a little wider to keep it looking like the original, but with some extra side background to make it a square.

**Comment by ZakGriffith** [comment]
A *rounded* square, hah.  Like the other Icons.

**Comment by escottalexander** [comment]
The latest updates look good to me but I am not quite sure what @ZakGriffith was seeing.

**Review by ZakGriffith — APPROVED** [review]
Updates to the icon look good!

**Pull request merged**
