### PR TITLE
Dark modal fix

### LINKED ISSUE #112: Dark mode issues with Edit Distribution and Add List To Ballot modals
We need to fix the dark mode version of these two modals.

Edit Distribution:
image

Add List To Ballot:
image

### PR DESCRIPTION
**Pull request by KcPele**
## Description
Dark theme modal fix
#112 
_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

### CODE REVIEW

**Review by escottalexander — CHANGES_REQUESTED** [review]
This looks great except the "add to ballot" modal has this: 
image

I would make it just like the edit distribution modal:
image

**Comment by escottalexander** [comment]
Also noticed these places. It is really hard to see the text. Maybe it should turn white when in dark mode? Or just a lighter shade of grey.

image

image

image

**Comment by ZakGriffith** [comment]
This is looking better to me!

**Review by escottalexander — APPROVED** [review]
LGTM! I fixed the merge conflicts.

**Pull request merged**
